// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XHelper
{
    static class Vsix
    {
        public const string Id = "d7c3f904-cc5a-4d47-aa25-81fb7c36df89";
        public const string Name = "XML Helper";
        public const string Description = @"Provides clean way to decode <,>,&<,&gt; >";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Nikhil Khurana";
        public const string Tags = "comment, cleanup, delete, region, XMLDoc";
    }
}
