// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XHelper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "34f42dd5-2285-4902-bdfa-6d721e867b57";
        public const string guidXmlUiCmdsString = "fb87333b-16c8-400e-bc8f-f6b890410582";
        public const string guidPackageCmdSetString = "d7952971-879b-431d-b743-70ad7e99e846";
        public const string guidXHelperPackageCmdSetString = "665ffd9b-e27f-4a1d-b5d9-e35bd8c587ed";
        public const string guidImagesString = "358b0570-7cd6-429a-a34e-363ed4c225ce";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidXmlUiCmds = new Guid(guidXmlUiCmdsString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
        public static Guid guidXHelperPackageCmdSet = new Guid(guidXHelperPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenu = 0x1000;
        public const int CommentsGroup = 0x1020;
        public const int XmlConversionGroup = 0x1060;
        public const int RemoveAllComments = 0x0100;
        public const int XmlConversion = 0x0700;
        public const int cmdidEBCXSDebuggerCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
